### ISSUE TITLE
Bug on running smartcrop

### ISSUE THREAD

**Issue by weiztech** [epixelic/python-smart-crop#1]
```
  File "/home/jensen/bidkan-env/lib/python3.5/site-packages/smartcrop/__init__.py", line 167, in smart_crop
    cropped = original[crop_pos['top']: crop_pos['bottom'], crop_pos['left']: crop_pos['right']]
TypeError: slice indices must be integers or None or have an __index__ method
```

Hi i tested the command `smartcrop` and get issues above. i checked it because `float` value
`Crop rectangle is {'top': 198.86, 'right': 640, 'left': 0, 'bottom': 838.86}`

to fix it, i edit the float value to int ex: `int(crop_pos['top'])`

could you update the module ? 

anyway the module looks Great!. its really help me!

**Comment by drzraf** [comment]
Idem here:
```
$ file a.jpg
JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=0], baseline, precision 8, 700x459, frames 3
$ smartcrop
Image resized by -318.73638344226583 * -209.0 in 2 pass(es)
Using Good Feature Tracking method
Found center at {'x': 174.81999999999999, 'y': 127.08, 'count': 50}
Crop rectangle is {'left': 49.819999999999993, 'right': 299.81999999999999, 'top': 1.4210854715202004e-14, 'bottom': 250}
```

**Comment by epx-jgonzalez** [comment]
Hi ! Thanks for your interest in my module.
I didn't receive any notification for your issue, sorry ^^". I just updated the code.
Feel free to open a PR or another issue if there is still a problem !
 Thanks a lot :) !
